volumes:
  asterisk_logs:

services:
  asterisk:
    image: 841209751833.dkr.ecr.eu-central-1.amazonaws.com/la-asterisk:latest
    group_add:
      - "117"   
    network_mode: host
    volumes:
      - asterisk_logs:/var/log/asterisk
      - /etc/asterisk/:/etc/asterisk/:ro

      - /etc/odbc.ini:/etc/odbc.ini:ro
      - /etc/odbcinst.ini:/etc/odbcinst.ini

      - /etc/pki/tls/certs/asterisk.pem:/etc/pki/tls/certs/asterisk.pem:ro

      - /usr/share/asterisk/moh/:/usr/share/asterisk/moh/:ro
    # restart: unless-stopped
