[global]
type=global
user_agent=Ladesk Media GW

[general]
tlsenable=yes
tcpenable=yes
tcpbindaddr={{ fqdn }}
transport=udp,tcp

[transport-udp]
type=transport
protocol=udp
bind={{ fqdn }}
external_media_address={{ publicIp }}
external_signaling_address={{ publicIp }}

[transport-tcp]
type=transport
protocol=tcp
bind={{ fqdn }}
external_media_address={{ publicIp }}
external_signaling_address={{ publicIp }}

[transport-tls]
type=transport
protocol=tls
bind={{ fqdn }}
cert_file=/etc/pki/tls/certs/asterisk.pem
priv_key_file=/etc/pki/tls/certs/asterisk.pem
external_media_address={{ publicIp }}
external_signaling_address={{ publicIp }}
