volumes:
  asterisk_logs:

services:
  asterisk:
    image: ghcr.io/andrius/asterisk:22.8.2_debian-trixie
    network_mode: host
    # ports:
    #   - "5060:5060/udp" # SIP UDP
    #   - "5060:5060/tcp" # SIP TCP
    #   - "5061:5061/tcp" # SIP TLS
    #   - "10000-31000:10000-31000/udp" # RTP Media (ensure these ports are open in firewall)
    volumes:
    # - ./asterisk/keys:/etc/asterisk/keys:ro
    # - ./config/modules.conf:/etc/asterisk/modules.conf:ro
      - asterisk_logs:/var/log/asterisk
      - ./config/asterisk.conf:/etc/asterisk/asterisk.conf:ro
      - ./config/hep.conf:/etc/asterisk/hep.conf:ro
      - ./config/logger.conf:/etc/asterisk/logger.conf:ro
      - ./config/ari.conf:/etc/asterisk/ari.conf:ro
      - ./config/http.conf:/etc/asterisk/http.conf:ro
      - ./config/extconfig.conf:/etc/asterisk/extconfig.conf:ro
      - ./config/musiconhold.conf:/etc/asterisk/musiconhold.conf:ro
      - ./config/pjsip.conf:/etc/asterisk/pjsip.conf:ro
      - ./config/res_odbc.conf:/etc/asterisk/res_odbc.conf:ro
      - ./config/rtp.conf:/etc/asterisk/rtp.conf:ro
      - ./config/sorcery.conf:/etc/asterisk/sorcery.conf:ro

      - /etc/pki/tls/certs/asterisk.pem:/etc/pki/tls/certs/asterisk.pem:ro
      - /etc/pki/tls/private/asterisk.key:/etc/pki/tls/private/asterisk.key:ro
    # env_file: .env
    # restart: unless-stopped
